# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02404bf30c07b73b232a7721ed21eddc3ffd0b935cad1858a75af24f50641657bd1c50402f55399eed1ef9bc8a11ee817b739e460f1faae07a28ccd2b031f896

test:
  secret_key_base: 3265d830b052c026e0d38b7e9f80a888b973776b0507a827ae31a4372ac44438f0827d47bcfd103abdd48b1b228dffcb874dd2641b8cfaba7bfb983ec0d6bc72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
